import mongoose from "mongoose";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
dotenv.config({ path: join(__dirname, ".env") });

const productSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: Array, required: true },
  price: { type: Number, required: true },
  offerPrice: { type: Number, required: true },
  image: { type: Array, required: true },
  category: { type: String, required: true },
  inStock: { type: Boolean, required: true, default: true },
});

const Product = mongoose.model("Product", productSchema);

const img = (id) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=600&q=80`;

const products = [
  // ─── Electronics ──────────────────────────────────────────────
  {
    name: "Wireless Earbuds",
    category: "Electronics",
    price: 3999,
    offerPrice: 2999,
    inStock: true,
    image: [img("1590658268037-6bf12165e8df")],
    description: ["Active noise cancellation", "30-hour battery life", "IPX5 water resistant"],
  },
  {
    name: "Smart Watch",
    category: "Electronics",
    price: 8999,
    offerPrice: 6999,
    inStock: true,
    image: [img("1523275335684-37898b6baf30")],
    description: ["Heart rate & SpO2 monitor", "7-day battery", "100+ workout modes"],
  },
  {
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    price: 4500,
    offerPrice: 3200,
    inStock: true,
    image: [img("1608043152269-423dbba4e7e1")],
    description: ["360° surround sound", "12-hour playtime", "Waterproof design"],
  },
  {
    name: "Power Bank 20000mAh",
    category: "Electronics",
    price: 2999,
    offerPrice: 1999,
    inStock: true,
    image: [img("1618492637163-05d0a6a35e2c")],
    description: ["Fast charging 22.5W", "Dual USB-C ports", "LED power indicator"],
  },
  {
    name: "USB-C Hub 7-in-1",
    category: "Electronics",
    price: 3500,
    offerPrice: 2500,
    inStock: true,
    image: [img("1625251899716-3b3d02cad4c6")],
    description: ["HDMI 4K output", "3x USB 3.0 ports", "SD & microSD card reader"],
  },
  {
    name: "Smart LED Bulb",
    category: "Electronics",
    price: 799,
    offerPrice: 599,
    inStock: true,
    image: [img("1550009158-9ebf69173e03")],
    description: ["16M colour options", "Voice control compatible", "Energy saving A+"],
  },

  // ─── Beauty & Care ────────────────────────────────────────────
  {
    name: "Vitamin C Face Serum 30ml",
    category: "Beauty",
    price: 1299,
    offerPrice: 999,
    inStock: true,
    image: [img("1608248543803-ba4a8b7a1b30")],
    description: ["Brightens skin tone", "Reduces dark spots", "Dermatologist tested"],
  },
  {
    name: "Hydrating Face Moisturiser 50ml",
    category: "Beauty",
    price: 899,
    offerPrice: 699,
    inStock: true,
    image: [img("1596462502278-27bfdc403348")],
    description: ["24-hour hydration", "SPF 30 protection", "Suitable for all skin types"],
  },
  {
    name: "Matte Lipstick Set (6 pcs)",
    category: "Beauty",
    price: 1500,
    offerPrice: 999,
    inStock: true,
    image: [img("1586495777744-4e6b8c72d25d")],
    description: ["Long-lasting formula", "6 trendy shades", "Cruelty-free"],
  },
  {
    name: "Argan Oil Hair Mask 200ml",
    category: "Beauty",
    price: 799,
    offerPrice: 599,
    inStock: true,
    image: [img("1522338242992-e1d3e6a78455")],
    description: ["Deep conditioning", "Reduces frizz", "Suitable for all hair types"],
  },
  {
    name: "Electric Face Cleanser Brush",
    category: "Beauty",
    price: 2500,
    offerPrice: 1799,
    inStock: true,
    image: [img("1570172619644-dfd03ed5d881")],
    description: ["3 cleaning modes", "Waterproof silicone head", "Removes 99.5% impurities"],
  },
  {
    name: "Perfume 100ml",
    category: "Beauty",
    price: 2999,
    offerPrice: 2299,
    inStock: true,
    image: [img("1541643600914-78b084683702")],
    description: ["Long-lasting fragrance", "Floral & woody notes", "Elegant bottle design"],
  },

  // ─── Computers ────────────────────────────────────────────────
  {
    name: "Laptop 15.6\" Core i5",
    category: "Computers",
    price: 89999,
    offerPrice: 74999,
    inStock: true,
    image: [img("1496181133206-80ce9b88a853")],
    description: ["Intel Core i5 12th Gen", "8GB RAM / 512GB SSD", "Full HD IPS display"],
  },
  {
    name: "Mechanical Gaming Keyboard",
    category: "Computers",
    price: 7999,
    offerPrice: 5999,
    inStock: true,
    image: [img("1587829741301-dc798b83add3")],
    description: ["RGB backlight", "Blue switches", "Anti-ghosting 104 keys"],
  },
  {
    name: "Wireless Mouse",
    category: "Computers",
    price: 1999,
    offerPrice: 1399,
    inStock: true,
    image: [img("1527864550417-7fd91fc51a46")],
    description: ["2.4GHz wireless", "12-month battery life", "Ergonomic design"],
  },
  {
    name: "27\" 4K Monitor",
    category: "Computers",
    price: 39999,
    offerPrice: 32999,
    inStock: true,
    image: [img("1593640408182-31c4b34b2f2a")],
    description: ["3840x2160 UHD", "144Hz refresh rate", "HDR 400 certified"],
  },
  {
    name: "External SSD 1TB",
    category: "Computers",
    price: 9999,
    offerPrice: 7499,
    inStock: true,
    image: [img("1597852074816-d8c7b7f68c4c")],
    description: ["1050 MB/s read speed", "USB 3.2 Gen 2", "Shock resistant"],
  },
  {
    name: "Laptop Stand Adjustable",
    category: "Computers",
    price: 1999,
    offerPrice: 1299,
    inStock: true,
    image: [img("1625296276703-3fbc5ba2e84d")],
    description: ["6 height levels", "Aluminium alloy", "Foldable & portable"],
  },

  // ─── Fashion ──────────────────────────────────────────────────
  {
    name: "Men's Cotton T-Shirt",
    category: "Fashion",
    price: 799,
    offerPrice: 499,
    inStock: true,
    image: [img("1521572163474-6864f9cf17ab")],
    description: ["100% premium cotton", "Regular fit", "Available in 8 colours"],
  },
  {
    name: "Women's Kurti",
    category: "Fashion",
    price: 1299,
    offerPrice: 899,
    inStock: true,
    image: [img("1583391265891-7a3e01e5f4e4")],
    description: ["Breathable rayon fabric", "Floral print", "Sizes XS to 3XL"],
  },
  {
    name: "Denim Jeans (Men)",
    category: "Fashion",
    price: 2999,
    offerPrice: 1999,
    inStock: true,
    image: [img("1542272604-787c3835535d")],
    description: ["Slim fit stretch denim", "5-pocket design", "Machine washable"],
  },
  {
    name: "Running Sneakers",
    category: "Fashion",
    price: 4999,
    offerPrice: 3499,
    inStock: true,
    image: [img("1542291026-7eec264c27ff")],
    description: ["Lightweight mesh upper", "Cushioned sole", "Anti-slip grip"],
  },
  {
    name: "Leather Handbag",
    category: "Fashion",
    price: 3999,
    offerPrice: 2799,
    inStock: true,
    image: [img("1548036161-65dc29780f22")],
    description: ["Genuine PU leather", "Multiple compartments", "Adjustable strap"],
  },
  {
    name: "Wristwatch (Analogue)",
    category: "Fashion",
    price: 2499,
    offerPrice: 1799,
    inStock: true,
    image: [img("1524592094714-0f0654e359cf")],
    description: ["Stainless steel case", "Mineral crystal glass", "Water resistant 30m"],
  },

  // ─── Home & Kitchen ───────────────────────────────────────────
  {
    name: "Non-Stick Cookware Set (5 pcs)",
    category: "Home",
    price: 5999,
    offerPrice: 3999,
    inStock: true,
    image: [img("1556909114-f6e7ad7d3136")],
    description: ["PFOA-free coating", "Induction compatible", "Dishwasher safe"],
  },
  {
    name: "Air Fryer 4L",
    category: "Home",
    price: 7999,
    offerPrice: 5499,
    inStock: true,
    image: [img("1585515656945-6b5f71de4d2d")],
    description: ["80% less oil", "Rapid air technology", "Digital touch screen"],
  },
  {
    name: "Vacuum Cleaner 2200W",
    category: "Home",
    price: 8999,
    offerPrice: 6499,
    inStock: true,
    image: [img("1558618666-fcd25c85cd64")],
    description: ["HEPA filtration", "Bagless design", "Multiple attachments"],
  },
  {
    name: "Bedsheet Set (King Size)",
    category: "Home",
    price: 1999,
    offerPrice: 1299,
    inStock: true,
    image: [img("1631049307264-da0ec9d70304")],
    description: ["400 thread count cotton", "Includes 2 pillowcases", "Machine washable"],
  },
  {
    name: "Electric Kettle 1.5L",
    category: "Home",
    price: 1299,
    offerPrice: 899,
    inStock: true,
    image: [img("1570222094114-d054a817e56b")],
    description: ["2200W fast boil", "Auto shut-off", "360° cordless base"],
  },
  {
    name: "Indoor Plant Pot (Set of 3)",
    category: "Home",
    price: 999,
    offerPrice: 699,
    inStock: true,
    image: [img("1485955900006-10f4d324d411")],
    description: ["Ceramic finish", "Drainage holes included", "Modern minimalist design"],
  },

  // ─── Sports ───────────────────────────────────────────────────
  {
    name: "Yoga Mat 6mm",
    category: "Sports",
    price: 1499,
    offerPrice: 999,
    inStock: true,
    image: [img("1518611012118-696072aa579a")],
    description: ["Anti-slip surface", "Extra thick 6mm", "Includes carry strap"],
  },
  {
    name: "Adjustable Dumbbell Set 20kg",
    category: "Sports",
    price: 5999,
    offerPrice: 4299,
    inStock: true,
    image: [img("1534438327276-14e5300c3a48")],
    description: ["Cast iron with rubber grip", "Quick-adjust mechanism", "10 weight settings"],
  },
  {
    name: "Cycling Helmet",
    category: "Sports",
    price: 2999,
    offerPrice: 1999,
    inStock: true,
    image: [img("1576858574144-9ae1ebcf5ae5")],
    description: ["In-mould EPS liner", "12 ventilation channels", "Adjustable fit system"],
  },
  {
    name: "Badminton Racket Set",
    category: "Sports",
    price: 1499,
    offerPrice: 999,
    inStock: true,
    image: [img("1617083934551-d851e64b83c5")],
    description: ["2 rackets + 3 shuttlecocks", "Aluminium frame", "Includes carry bag"],
  },
  {
    name: "Running Water Bottle 750ml",
    category: "Sports",
    price: 699,
    offerPrice: 499,
    inStock: true,
    image: [img("1523362628745-0c100150b504")],
    description: ["BPA-free Tritan plastic", "Leak-proof lid", "Flip-top straw"],
  },
  {
    name: "Resistance Bands Set (5 pcs)",
    category: "Sports",
    price: 899,
    offerPrice: 599,
    inStock: true,
    image: [img("1571019613454-1cb2f99b2d8b")],
    description: ["5 resistance levels", "Latex-free", "Full body workout"],
  },

  // ─── Cloned Sports into other categories (so they exist without DB run) ───
  // Each original Sports product is duplicated into: Grocery, Meat, Beauty, Kitchen, Garments, Baby Items
  {
    name: "Basmati Rice 1kg",
    category: "Grocery",
    price: 420,
    offerPrice: 350,
    inStock: true,
    image: ["/images/basmati-rice-1kg.png"],
    description: ["Premium long grain", "Ideal for biryani", "Aromatic basmati rice"],
  },
  {
    name: "Chicken Drumsticks 500g",
    category: "Meat",
    price: 599,
    offerPrice: 499,
    inStock: true,
    image: [img("1518611012118-696072aa579a")],
    description: ["Fresh farm chicken", "Juicy and tender", "Perfect for grilling"],
  },
  {
    name: "Yoga Mat 6mm",
    category: "Beauty",
    price: 1499,
    offerPrice: 999,
    inStock: true,
    image: [img("1518611012118-696072aa579a")],
    description: ["Anti-slip surface", "Extra thick 6mm", "Includes carry strap"],
  },
  {
    name: "Yoga Mat 6mm",
    category: "Kitchen",
    price: 1499,
    offerPrice: 999,
    inStock: true,
    image: [img("1518611012118-696072aa579a")],
    description: ["Anti-slip surface", "Extra thick 6mm", "Includes carry strap"],
  },
  {
    name: "Striped Polo Shirt",
    category: "Garments",
    price: 1950,
    offerPrice: 1333,
    inStock: true,
    image: ["/images/striped-polo-shirt.png"],
    description: ["Anti-slip surface", "Extra thick 6mm", "Includes carry strap"],
  },
  {
    name: "Soft Baby Blanket",
    category: "Baby Items",
    price: 2380,
    offerPrice: 1999,
    inStock: true,
    image: ["/images/soft-baby-blanket.png"],
    description: ["Anti-slip surface", "Extra thick 6mm", "Includes carry strap"],
  },

  {
    name: "Fresh Chicken 1kg",
    category: "Grocery",
    price: 430,
    offerPrice: 390,
    inStock: true,
    image: ["/images/fresh-chicken-1kg.png"],
    description: ["Farm fresh", "Cleaned and packed", "Ready for cooking"],
  },
  {
    name: "Beef Steak 1kg",
    category: "Meat",
    price: 2350,
    offerPrice: 1999,
    inStock: true,
    image: [img("1534438327276-14e5300c3a48")],
    description: ["Premium beef steak", "Rich in flavor", "Cook to preferred doneness"],
  },
  {
    name: "Adjustable Dumbbell Set 20kg",
    category: "Beauty",
    price: 5999,
    offerPrice: 4299,
    inStock: true,
    image: [img("1534438327276-14e5300c3a48")],
    description: ["Cast iron with rubber grip", "Quick-adjust mechanism", "10 weight settings"],
  },
  {
    name: "Adjustable Dumbbell Set 20kg",
    category: "Kitchen",
    price: 5999,
    offerPrice: 4299,
    inStock: true,
    image: [img("1534438327276-14e5300c3a48")],
    description: ["Cast iron with rubber grip", "Quick-adjust mechanism", "10 weight settings"],
  },
  {
    name: "Women's Slim Fit Jeans",
    category: "Garments",
    price: 4999,
    offerPrice: 4400,
    inStock: true,
    image: ["/images/womens-slim-fit-jeans.png"],
    description: ["Cast iron with rubber grip", "Quick-adjust mechanism", "10 weight settings"],
  },
  {
    name: "Organic Baby Lotion",
    category: "Baby Items",
    price: 620,
    offerPrice: 550,
    inStock: true,
    image: ["/images/organic-baby-lotion.png"],
    description: ["Cast iron with rubber grip", "Quick-adjust mechanism", "10 weight settings"],
  },

  {
    name: "Fresh Milk 1L",
    category: "Grocery",
    price: 399,
    offerPrice: 350,
    inStock: true,
    image: ["/images/fresh-milk-1l.png"],
    description: ["Full cream milk", "Pasteurised", "Rich in calcium"],
  },
  {
    name: "Fresh Fish 1kg",
    category: "Meat",
    price: 1250,
    offerPrice: 899,
    inStock: true,
    image: [img("1576858574144-9ae1ebcf5ae5")],
    description: ["Ocean-fresh fish", "Rich in protein", "Great for pan-frying"],
  },
  {
    name: "Cycling Helmet",
    category: "Beauty",
    price: 2999,
    offerPrice: 1999,
    inStock: true,
    image: [img("1576858574144-9ae1ebcf5ae5")],
    description: ["In-mould EPS liner", "12 ventilation channels", "Adjustable fit system"],
  },
  {
    name: "Cycling Helmet",
    category: "Kitchen",
    price: 2999,
    offerPrice: 1999,
    inStock: true,
    image: [img("1576858574144-9ae1ebcf5ae5")],
    description: ["In-mould EPS liner", "12 ventilation channels", "Adjustable fit system"],
  },
  {
    name: "Casual Hooded Sweatshirt",
    category: "Garments",
    price: 6300,
    offerPrice: 5220,
    inStock: true,
    image: ["/images/casual-hooded-sweatshirt.png"],
    description: ["In-mould EPS liner", "12 ventilation channels", "Adjustable fit system"],
  },
  {
    name: "Baby Stroller",
    category: "Baby Items",
    price: 8300,
    offerPrice: 6900,
    inStock: true,
    image: ["/images/baby-stroller.png"],
    description: ["In-mould EPS liner", "12 ventilation channels", "Adjustable fit system"],
  },

  {
    name: "Cooking Oil 1L",
    category: "Grocery",
    price: 640,
    offerPrice: 615,
    inStock: true,
    image: ["/images/cooking-oil-1l.png"],
    description: ["Refined cooking oil", "Suitable for frying", "1 litre bottle"],
  },
  {
    name: "Chicken Sausages 500g",
    category: "Meat",
    price: 1500,
    offerPrice: 1299,
    inStock: true,
    image: [img("1617083934551-d851e64b83c5")],
    description: ["Smoked chicken sausages", "Ready to cook", "Perfect for breakfast"],
  },
  {
    name: "Badminton Racket Set",
    category: "Beauty",
    price: 1499,
    offerPrice: 999,
    inStock: true,
    image: [img("1617083934551-d851e64b83c5")],
    description: ["2 rackets + 3 shuttlecocks", "Aluminium frame", "Includes carry bag"],
  },
  {
    name: "Badminton Racket Set",
    category: "Kitchen",
    price: 1499,
    offerPrice: 999,
    inStock: true,
    image: [img("1617083934551-d851e64b83c5")],
    description: ["2 rackets + 3 shuttlecocks", "Aluminium frame", "Includes carry bag"],
  },
  {
    name: "Floral Maxi Dress",
    category: "Garments",
    price: 9999,
    offerPrice: 6800,
    inStock: true,
    image: ["/images/floral-maxi-dress.png"],
    description: ["2 rackets + 3 shuttlecocks", "Aluminium frame", "Includes carry bag"],
  },
  {
    name: "Baby Diaper Pack",
    category: "Baby Items",
    price: 1280,
    offerPrice: 1150,
    inStock: true,
    image: ["/images/baby-diaper-pack.png"],
    description: ["2 rackets + 3 shuttlecocks", "Aluminium frame", "Includes carry bag"],
  },

  {
    name: "Whole Wheat Flour 1kg",
    category: "Grocery",
    price: 310,
    offerPrice: 250,
    inStock: true,
    image: ["/images/whole-wheat-flour-1kg.png"],
    description: ["Atta", "Stone ground", "1 kilogram pack"],
  },
  {
    name: "Eggs Dozen",
    category: "Grocery",
    price: 250,
    offerPrice: 199,
    inStock: true,
    image: [img("1523362628745-0c100150b504")],
    description: ["Farm fresh eggs", "12-pack", "Rich in protein"],
  },
  {
    name: "Running Water Bottle 750ml",
    category: "Beauty",
    price: 699,
    offerPrice: 499,
    inStock: true,
    image: [img("1523362628745-0c100150b504")],
    description: ["BPA-free Tritan plastic", "Leak-proof lid", "Flip-top straw"],
  },
  {
    name: "Running Water Bottle 750ml",
    category: "Kitchen",
    price: 699,
    offerPrice: 499,
    inStock: true,
    image: [img("1523362628745-0c100150b504")],
    description: ["BPA-free Tritan plastic", "Leak-proof lid", "Flip-top straw"],
  },
  {
    name: "Chambray Button-Down Shirt",
    category: "Garments",
    price: 1975,
    offerPrice: 1499,
    inStock: true,
    image: ["/images/chambray-button-down-shirt.png"],
    description: ["BPA-free Tritan plastic", "Leak-proof lid", "Flip-top straw"],
  },
  {
    name: "Baby Feeding Bottle",
    category: "Baby Items",
    price: 1650,
    offerPrice: 1300,
    inStock: true,
    image: ["/images/baby-feeding-bottle.png"],
    description: ["BPA-free Tritan plastic", "Leak-proof lid", "Flip-top straw"],
  },

  // ─── Books ────────────────────────────────────────────────────
  {
    name: "Atomic Habits",
    category: "Books",
    price: 599,
    offerPrice: 399,
    inStock: true,
    image: [img("1512820790803-83ca734da794")],
    description: ["By James Clear", "Build good habits & break bad ones", "Bestseller #1 worldwide"],
  },
  {
    name: "Rich Dad Poor Dad",
    category: "Books",
    price: 499,
    offerPrice: 349,
    inStock: true,
    image: [img("1544716278-ca5e3f4abd8c")],
    description: ["By Robert Kiyosaki", "Financial literacy masterclass", "Over 32 million copies sold"],
  },
  {
    name: "The Psychology of Money",
    category: "Books",
    price: 549,
    offerPrice: 379,
    inStock: true,
    image: [img("1481627834876-b7833e8f5570")],
    description: ["By Morgan Housel", "Timeless lessons on wealth", "200+ weeks on bestseller list"],
  },
  {
    name: "Deep Work",
    category: "Books",
    price: 499,
    offerPrice: 329,
    inStock: true,
    image: [img("1507003211169-0a1dd7228f2d")],
    description: ["By Cal Newport", "Rules for focused success", "Transform your productivity"],
  },
  {
    name: "Think and Grow Rich",
    category: "Books",
    price: 299,
    offerPrice: 199,
    inStock: true,
    image: [img("1535905557558-19f073745b26")],
    description: ["By Napoleon Hill", "Timeless success principles", "Over 100 million copies"],
  },
  {
    name: "Python Programming (Beginner to Pro)",
    category: "Books",
    price: 799,
    offerPrice: 549,
    inStock: true,
    image: [img("1526374965328-7f61d4dc18c5")],
    description: ["Complete Python guide", "Covers data science & web dev", "Includes 50+ projects"],
  },

  // ─── Toys & Games ─────────────────────────────────────────────
  {
    name: "LEGO Classic Bricks 1000 pcs",
    category: "Toys",
    price: 4999,
    offerPrice: 3599,
    inStock: true,
    image: [img("1558060370-d644479cb6f7")],
    description: ["1000 classic bricks", "Ages 4+", "Sparks creativity & imagination"],
  },
  {
    name: "Remote Control Car",
    category: "Toys",
    price: 2999,
    offerPrice: 1999,
    inStock: true,
    image: [img("1611500815049-e93e2b3f8b7f")],
    description: ["30km/h top speed", "All-terrain tyres", "40-min rechargeable battery"],
  },
  {
    name: "Jigsaw Puzzle 1000 pcs",
    category: "Toys",
    price: 1299,
    offerPrice: 899,
    inStock: true,
    image: [img("1546623668-3325851be678")],
    description: ["Premium quality pieces", "Ages 8+", "Finished size 70x50cm"],
  },
  {
    name: "Board Game — Monopoly",
    category: "Toys",
    price: 1999,
    offerPrice: 1399,
    inStock: true,
    image: [img("1611996575749-79e1e37a7d07")],
    description: ["2-6 players", "Classic property trading", "Family game night favourite"],
  },
  {
    name: "Stuffed Teddy Bear 45cm",
    category: "Toys",
    price: 799,
    offerPrice: 549,
    inStock: true,
    image: [img("1559454403-b8fb88a36e5e")],
    description: ["Ultra soft plush", "Machine washable", "Safe for all ages"],
  },
  {
    name: "Wooden Blocks Set 50 pcs",
    category: "Toys",
    price: 1499,
    offerPrice: 999,
    inStock: true,
    image: [img("1587654780291-392ced7e2c56")],
    description: ["Non-toxic natural wood", "Ages 1+", "Develops motor skills"],
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    const existing = await Product.countDocuments();
    if (existing > 0) {
      await Product.deleteMany({});
      console.log(`Cleared ${existing} existing products`);
    }


    const approvedCategories = new Set([
      "Electronics",
      "Sports",
      "Grocery",
      "Meat",
      "Beauty",
      "Kitchen",
      "Garments",
      "Baby Items",
    ]);
    const productsToSeed = products.filter((product) => approvedCategories.has(product.category));
    const inserted = await Product.insertMany(productsToSeed);
    console.log(`\nSeeded ${inserted.length} products across ${approvedCategories.size} categories:\n`);

    const cats = [...new Set(productsToSeed.map((p) => p.category))];
    for (const cat of cats) {
      const count = productsToSeed.filter((p) => p.category === cat).length;
      console.log(`  ${cat}: ${count} products`);
    }

    console.log("\nDone!");
  } catch (err) {
    console.error("Seed error:", err.message);
  } finally {
    await mongoose.disconnect();
  }
}

seed();
